#!/bin/sh

set -e

if ! git diff-index --quiet HEAD --; then
  echo "tree is dirty, please commit changes before building"
  exit 1
fi

script/lint

script/test

webpack

if ! git diff-index --quiet HEAD --; then
  echo $?
   echo "UNCLEAN"
   git status
    git add docs/*
    git commit -m 'Update demo files for ghpages'
fi

echo "Done"
